name: CharaStadio
options:
  bundleIdPrefix: fuya.CharaStadio
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: ja
  xcodeVersion: "12.3"
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  CharaStadio:
    type: application
    platform: iOS
    sources: CharaStadio
    configFiles:
      Debug: configs/CharaStadio-Debug.xcconfig
      Release: configs/CharaStadio-Release.xcconfig
    settings:
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.2
      TARGETED_DEVICE_FAMILY: 1
