name: CharaStadio
options:
  bundleIdPrefix: fuya.CharaStadio
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: ja
  xcodeVersion: "12.3"
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig

targets:
  CharaStadio:
    type: application
    platform: iOS
    sources: CharaStadio
    configFiles:
      Debug: configs/CharaStadio-Debug.xcconfig
      Release: configs/CharaStadio-Release.xcconfig
    settings:
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.5
      TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - target: CharaStadioStickers
        embed: true
        codeSign: false
        buildPhase:
          copyFiles:
            destination: plugins

  CharaStadioStickers:
    type: app-extension.messages-sticker-pack
    platform: iOS
    deploymentTarget: 11.0
    sources:
      - CharaStadioStickers
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: "iMessage App Icon"
        CLANG_ENABLE_OBJC_WEAK: YES
        CODE_SIGN_IDENTITY: "iPhone Developer"
        CODE_SIGN_STYLE: Automatic
        GCC_PREPROCESSOR_DEFINITIONS:
          - "DEBUG=1"
          - "$(inherited)"
        INFOPLIST_FILE: CharaStadioStickers/Info.plist
        LD_RUNPATH_SEARCH_PATHS: ""
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        MTL_FAST_MATH: YES
        PRODUCT_BUNDLE_IDENTIFIER: fuya.CharaStadio.sticker
        PRODUCT_NAME: "YanArt"
        SKIP_INSTALL: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.5

schemes:
  CharaStadio:
    build:
      targets:
        CharaStadio: all